/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\smallTable.gltf 
Author: Fridqeir (https://sketchfab.com/Fridqeir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-table-f734a4032a264674853eb549f5567796
Title: Small Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SmallTable(props) {
  const { nodes, materials } = useGLTF('/smallTable.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/smallTable.gltf')
