/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\table.gltf 
Author: Thomas Binder (https://sketchfab.com/bindertom61)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-small-birch-coffee-table-dd779b37e7514e9688a9fa9d0c8142fb
Title: Table - small birch coffee table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/table.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.table_wood} position={[0, 0.931, 0]} scale={[1, 1, 4.034]} />
    </group>
  )
}

useGLTF.preload('/table.gltf')
